cp sign_plate_round_green.svg sign_left_green.svg
cp sign_plate_round_green.svg sign_right_green.svg
cp sign_plate_round_green.svg sign_up_green.svg
cp sign_plate_round_green.svg sign_down_green.svg
cp sign_plate_round_green.svg sign_exlamation_green.svg
cp sign_plate_round_green.svg sign_info_green.svg
cp sign_plate_round_green.svg sign_no_entry_green.svg

cp sign_plate_round_green_small.svg sign_left_green_small.svg
cp sign_plate_round_green_small.svg sign_right_green_small.svg
cp sign_plate_round_green_small.svg sign_up_green_small.svg
cp sign_plate_round_green_small.svg sign_down_green_small.svg
cp sign_plate_round_green_small.svg sign_exlamation_green_small.svg
cp sign_plate_round_green_small.svg sign_info_green_small.svg
cp sign_plate_round_green_small.svg sign_no_entry_green_small.svg


